### ISSUE TITLE
Additional Knowlege Graphs App

### ISSUE THREAD

**Issue by navigator8** [brettkromkamp/knowledge-graph-radar#2]
Check these out:

- https://cotoa.me/

- https://www.digitalpage.me/

- http://notegraph.com/

- https://www.ideaflow.io/

- https://www.topincs.com/tour

- https://kamala.mssm.nl/topicmaps/

**Comment by brettkromkamp** [comment]
@navigator8 I’ll check them out and start adding to list.

**Comment by brettkromkamp** [comment]
Added them to the list of applications.
